# Generated by Django 3.1.1 on 2020-12-13 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='register_date',
            field=models.DateField(default=datetime.date(2020, 12, 13)),
        ),
    ]
