# Generated by Django 3.1.1 on 2020-12-18 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customer_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='register_date',
            field=models.DateField(default=datetime.date(2020, 12, 18)),
        ),
    ]
