# Generated by Django 3.1.1 on 2020-12-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201218_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='register_date',
            field=models.DateField(default=datetime.date(2020, 12, 19)),
        ),
    ]
