# Generated by Django 3.1.1 on 2020-12-05 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 0, 31, 13, 146716)),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateField(default=datetime.date(2020, 12, 6)),
        ),
    ]
