# Generated by Django 3.1.1 on 2020-12-13 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201206_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 8, 54, 4, 196091)),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateField(default=datetime.date(2020, 12, 13)),
        ),
    ]
