# Generated by Django 3.1.1 on 2020-12-13 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201213_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 8, 55, 50, 345141)),
        ),
    ]
