# Generated by Django 3.1.1 on 2020-12-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201218_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 21, 43, 22, 454923)),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateField(default=datetime.date(2020, 12, 19)),
        ),
    ]
