# Generated by Django 3.1.1 on 2020-12-04 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('order_date', models.DateField(default=datetime.date(2020, 12, 4))),
                ('order_time', models.TimeField(default=datetime.time(19, 58, 12, 629210))),
                ('status', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on delivery'), ('online', 'Online')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-order_date',),
            },
        ),
    ]
