# Generated by Django 3.1.1 on 2020-12-05 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.orders',),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 12, 6)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(default=datetime.time(0, 31, 13, 160031)),
        ),
    ]
