# Generated by Django 3.1.1 on 2020-12-13 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201206_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 12, 13)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(default=datetime.time(8, 54, 4, 204735)),
        ),
    ]
