# Generated by Django 3.1.1 on 2020-12-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201218_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.orders',),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 12, 19)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(default=datetime.time(21, 43, 22, 465710)),
        ),
    ]
